version: '3'
services:
  database:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: devops   
    ports:
      - 3306:3306
    networks:
     - AppNet
     
  spring-boot:
    image: mootezchachia1/devops
    container_name: spring
    ports:
      - 8082:8082
    depends_on:
      - database
    networks:
      - AppNet 
    restart: on-failure     

networks:
  AppNet:
